services:
  - type: web
    name: coinpulse-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coinpulse-db
          property: connectionString
      - key: CLOUDAMQP_URL
        sync: false

  - type: worker
    name: coinpulse-collector
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python collector.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coinpulse-db
          property: connectionString
      - key: CLOUDAMQP_URL
        sync: false

  - type: worker
    name: coinpulse-analyzer
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python analyzer.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coinpulse-db
          property: connectionString
      - key: CLOUDAMQP_URL
        sync: false

databases:
  - name: coinpulse-db
    plan: free